# Generated by Django 6.0.3 on 2026-03-09 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('5BHK', '5BHK')], max_length=10)),
                ('room_type', models.CharField(choices=[('Living Room', 'Living Room'), ('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Dining Room', 'Dining Room'), ('Study Room', 'Study Room'), ('Kids Room', 'Kids Room'), ('Balcony', 'Balcony'), ('Pooja Room', 'Pooja Room'), ('Guest Room', 'Guest Room')], max_length=50)),
                ('wall_color', models.CharField(max_length=50)),
                ('lamp_type', models.CharField(max_length=50)),
                ('furniture', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
