# Generated by Django 6.0.3 on 2026-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdesign',
            name='furniture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roomdesign',
            name='house_type',
            field=models.CharField(blank=True, choices=[('1RK', '1RK'), ('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('5BHK', '5BHK')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='roomdesign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roomdesign',
            name='lamp_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roomdesign',
            name='wall_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
